### ISSUE TITLE
TemplateCache.get is not a function

### ISSUE THREAD

**Issue by wumke** [marionettejs/marionette.templatecache#2]
I'm migrating an old project (Mn 1.4) to the latest Mn version. I liked the way the template was defined as a reference to a script tag that is included in html (server does translation things...), so I've added this library to my dependencies.

package.json:
```
"dependencies": {
    "backbone": "^1.4.0",
    "backbone.marionette": "^4.1.2",
    "marionette.templatecache": "^1.0.0",
    "underscore": "^1.9.1"
```
In my js file (I use webpack to build and package my js and css files):
```
const TemplateCache = require('marionette.templatecache');
const Marionette = require('backbone.marionette');
console.log(TemplateCache);
TemplateCache.get("#mytemplate");
```
Error in console: 
`Uncaught TypeError: TemplateCache.get is not a function`

Which is strange since I see the following as result of the console.log:
```
Module {__esModule: true, Symbol(Symbol.toStringTag): "Module", default: ƒ}
default: ƒ TemplateCache(templateId)
  arguments: (...)
  caller: (...)
  templateCaches: {}
  render: ƒ render(template, data)
  get: ƒ (templateId, options)
  clear: ƒ clear()
```
...which tells me that get IS a function?

What am I doing wrong?

**Comment by paulfalgout** [comment]
it has to do with your importer.  `const { default as TemplateCache } = require('marionette.templatecache');` should work.

**Comment by wumke** [comment]
(Aha! Now I notice the 'default' in the console log output...)

> it has to do with your importer. const { default as TemplateCache } = require('marionette.templatecache'); should work.

Webpack doesn't like that (default keyword):
```
Syntax Error: Unexpected keyword 'default' (1:8)

> 1 | const { default as TemplateCache } = require('marionette.templatecache');

```
My solution is importing like this:
```
const TemplateCache = require('marionette.templatecache').default;
```
